#!/usr/bin/env php
<?php

require 'bootstrap.php';

use Symfony\Component\Console\Application;
use Nutrition\Helper;

// -----------------------------------------------------------------------------

$app = new Application;
// scaning commands
$commandFiles = Helper::dirContent(__DIR__.'/command', true);
foreach ($commandFiles as $file) {
    $content = file_get_contents($file);

    // skip abstract
    if (preg_match('/abstract class/', $content)) {
        continue;
    }

    // get namespace
    $namespace = null;
    if (preg_match('/namespace ([\w\\\\]+)/', $content, $matches)) {
        $namespace = $matches[1].'\\';
    }

    // check first
    $command = $namespace . basename($file, '.php');
    if (false === class_exists($command)) {
        continue;
    }

    // add command
    $app->add(new $command);
}
unset($command, $commandFiles);

// fix argv
if (2 === $_SERVER['argc'] && '/' === $_SERVER['argv'][1]) {
    $_SERVER['argc'] = 1;
    array_pop($_SERVER['argv']);
}

$app->run();
