--
-- @desc Create tables
--

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `Configurations` (
    `ID` INT AUTO_INCREMENT NOT NULL,
    `Name` VARCHAR(30) NOT NULL,
    `Content` LONGTEXT NOT NULL,
    `CreatedAt` DATETIME DEFAULT NULL,
    `UpdatedAt` DATETIME DEFAULT NULL,
    CONSTRAINT `PK_Configuration` PRIMARY KEY (`ID`),
    CONSTRAINT `UC_Name` UNIQUE (`Name`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE `Posts` (
    `ID` INT AUTO_INCREMENT NOT NULL,
    `Slug` VARCHAR(250) NOT NULL,
    `Title` VARCHAR(200) NOT NULL,
    `Headline` VARCHAR(250) NOT NULL,
    `Content` LONGTEXT NOT NULL,
    `Type` VARCHAR(30) NOT NULL,
    `UserID` INT NULL DEFAULT NULL,
    `CreatedAt` DATETIME DEFAULT NULL,
    `UpdatedAt` DATETIME DEFAULT NULL,
    CONSTRAINT `PK_Post` PRIMARY KEY (`ID`),
    CONSTRAINT `UC_Slug` UNIQUE (`Slug`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE `Users` (
    `ID` INT AUTO_INCREMENT NOT NULL,
    `Name` VARCHAR(100) NOT NULL,
    `Username` VARCHAR(50) NOT NULL,
    `Email` VARCHAR(100) NOT NULL,
    `Password` VARCHAR(128) NOT NULL,
    `Expired` VARCHAR(10) NOT NULL DEFAULT 'off',
    `Blocked` VARCHAR(10) NOT NULL DEFAULT 'off',
    `Roles` LONGTEXT NOT NULL,
    `CreatedAt` DATETIME DEFAULT NULL,
    `UpdatedAt` DATETIME DEFAULT NULL,
    CONSTRAINT `PK_Users` PRIMARY KEY (`ID`),
    CONSTRAINT `UC_Username` UNIQUE (`Username`),
    CONSTRAINT `UC_Email` UNIQUE (`Email`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE `UserLogs` (
    `SessionID` VARCHAR(255) NOT NULL,
    `Data` TEXT NULL DEFAULT NULL,
    `Stamp` INTEGER NOT NULL,
    `Ip` VARCHAR(45) NOT NULL,
    `Agent` VARCHAR(200) NOT NULL,
    `UserID` INT NULL DEFAULT NULL,
    `Active` SMALLINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT `PK_UserLog` PRIMARY KEY (`SessionID`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE `Tasks` (
    `ID` BIGINT AUTO_INCREMENT NOT NULL,
    `Task` VARCHAR(50) NOT NULL,
    `Description` TEXT NULL DEFAULT NULL,
    `Progress` SMALLINT NOT NULL DEFAULT 0,
    `File` VARCHAR(100) NULL DEFAULT NULL,
    `UserID` INT NULL DEFAULT NULL,
    `CreatedAt` DATETIME DEFAULT NULL,
    `CompleteAt` DATETIME DEFAULT NULL,
    CONSTRAINT `PK_Task` PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS=1;
