--
-- @desc Reset database content
--

SET FOREIGN_KEY_CHECKS=0;

DELETE FROM setting;
ALTER TABLE setting AUTO_INCREMENT=1;

DELETE FROM post;
ALTER TABLE post AUTO_INCREMENT=1;

DELETE FROM user;
ALTER TABLE user AUTO_INCREMENT=1;

DELETE FROM user_log;

DELETE FROM task;
ALTER TABLE task AUTO_INCREMENT=1;

SET FOREIGN_KEY_CHECKS=1;
