--
-- @desc Create relation
--

SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE `Posts`
    ADD CONSTRAINT `FK_User` FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `UserLogs`
    ADD CONSTRAINT `FK_User` FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `Tasks`
    ADD CONSTRAINT `FK_User` FOREIGN KEY (`UserID`) REFERENCES `Users` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

SET FOREIGN_KEY_CHECKS=1;
