--
-- @desc Create tables
--

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE setting (
    id INT AUTO_INCREMENT NOT NULL,
    nama VARCHAR(30) NOT NULL,
    konten LONGTEXT NOT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE post (
    id INT AUTO_INCREMENT NOT NULL,
    slug VARCHAR(250) NOT NULL,
    title VARCHAR(200) NOT NULL,
    headline VARCHAR(250) NOT NULL,
    konten LONGTEXT NOT NULL,
    tipe VARCHAR(30) NOT NULL,
    user_id INT NULL DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE user (
    id INT AUTO_INCREMENT NOT NULL,
    nama VARCHAR(100) NOT NULL,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(128) NOT NULL,
    expired VARCHAR(10) NOT NULL DEFAULT 'off',
    blocked VARCHAR(10) NOT NULL DEFAULT 'off',
    roles LONGTEXT NOT NULL,
    created_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE user_log (
    session_id VARCHAR(255) NOT NULL,
    data TEXT NULL DEFAULT NULL,
    stamp INTEGER NOT NULL,
    ip VARCHAR(45) NOT NULL,
    agent VARCHAR(200) NOT NULL,
    user_id INT NULL DEFAULT NULL,
    active SMALLINT(1) NOT NULL DEFAULT 1,
    PRIMARY KEY(session_id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

CREATE TABLE task (
    id BIGINT AUTO_INCREMENT NOT NULL,
    task VARCHAR(50) NOT NULL,
    description TEXT NULL DEFAULT NULL,
    progress SMALLINT NOT NULL DEFAULT 0,
    file VARCHAR(100) NULL DEFAULT NULL,
    user_id INT NULL DEFAULT NULL,
    created_at DATETIME DEFAULT NULL,
    complete_at DATETIME DEFAULT NULL,
    PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

SET FOREIGN_KEY_CHECKS=1;
